#!/usr/bin/env sh

# Add or remove RADIUS clients
# These are e.g. Wifi access points that can query the RADIUS server

set -e
source ${SCRIPTDIR}/config.sh
source ${SCRIPTDIR}/sharedfunctions.sh

if [ "$#" -le 1 ]; then
    /usr/bin/printf "Add client: manageclients.sh add <name> <ip address or range (in CIDR notation> <password>\n"
    /usr/bin/printf "Use  \"-\" for autogenerated password.\n"
    /usr/bin/printf "Example usage: ./manageclients.sh add wifiaps 10.0.7.0/28 -\n"
    /usr/bin/printf "This generates an entry in the clients.conf file with name 'wifiaps',\n"
    /usr/bin/printf "accessable for RADIUS clients with IP's in the range from 10.0.7.1-10.0.7.15,\n"
    /usr/bin/printf "and a random password.\n"
    /usr/bin/printf "The password is in clear text in the clients.conf file.\n"
    /usr/bin/printf "To add default testing client from localhost:\n"
    /usr/bin/printf " ./manageclients.sh add localhost 127.0.0.1 testing123\n"
    /usr/bin/printf "Remove client: edit the clients.conf file in the ${RADIUSDIR} directory.\n"
    /usr/bin/printf "WARNING: the script doesn't do any checking. Only happy flow is tested.\n"
    exit 1
fi

add() {
    CLIENT=$1
    IP=$2

    if [ "$3" = "-" ]; then
        PASSWORD=$(password)
    else
        PASSWORD=$3
    fi

    /usr/bin/printf "The password for client(s) ${CLIENT} is: \n"
    /usr/bin/printf "${PASSWORD}\n"

    /bin/cat << EOF >> ${CLIENTSCONF}    
client ${CLIENT} {
        ipaddr = ${IP}
        proto = udp
        secret = ${PASSWORD}
        limit {
                max_connections = 16
                lifetime = 0
                idle_timeout = 30
        }
}

EOF
}

#    set_value "default_days" ${VALIDITY} ${CLIENTCONFIG}
#    set_value "input_password" ${PASSWORD} ${CLIENTCONFIG}
#    set_value "output_password" ${PASSWORD} ${CLIENTCONFIG}
#    set_value_in_section "client" "emailAddress" ${USER} ${CLIENTCONFIG}
#    set_value_in_section "client" "commonName" ${USER} ${CLIENTCONFIG}
#    cd ${CERTSDIR}
#    /usr/bin/make client.pem
#    /bin/cp client.p12 "/provision/${USER}.p12"
#    /usr/bin/printf "${USER} ${EMAIL} ${PASSWORD}\n" >> ${PASSWORDFILE}
#    /usr/bin/printf "The password for user ${USER} is: \n"
#    /usr/bin/printf "${PASSWORD}\n"
#    if [ ! "${VLAN}" = "NONE" ]; then
#        sed -i "1s/^/        Tunnel-Type = VLAN,\n        Tunnel-Medium-Type = IEEE-802,\n        Tunnel-Private-Group-ID = \"10\"\n\n/" ${USERFILE}
#    fi
#    sed -i "1s/^/${USER}\n/" ${USERFILE}
#}

if [ "$1" = "add" ]; then
    add $2 $3 $4
fi

